config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Cfa::Styleguide::Engine => "/cfa"

  root "pages#index"
  get "/download", to: "pages#download"
  get "/consent", to: "pages#consent"
  get "/upload", to: "clients#new"
  get "/admin", to: "admin#index"
  get "/admin/clients/:id/pdf", to: "admin#pdf", as: "pdf"
  post "/admin/clients/:id/mail_pdf", to: "admin#mail_pdf", as: "mail_pdf"

  resources :clients
  resources :feedbacks, only: [:new, :create]




  get "/minimal", to: "pages#minimal"
  get "/full", to: "pages#full"
  get "/complete", to: "pages#complete"
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id             :bigint           not null, primary key
#  city           :string
#  email          :string
#  email_opt_in   :boolean          default(FALSE)
#  mailed         :boolean          default(FALSE)
#  name           :string
#  office_choice  :string
#  phone          :string
#  state          :string
#  street_address :string
#  text_opt_in    :boolean          default(FALSE)
#  zip_code       :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Client < ApplicationRecord
  has_one_attached :document
  has_one :feedback

  validates :phone, ten_digit_phone_number: true, allow_blank: true
  validate :file_required
  validate :must_opt_in_to_one

  def file_required
    errors.add(:document, "Must choose a file") unless document.attached?
  end

  def must_opt_in_to_one
    if !text_opt_in && !email_opt_in
      errors.add(:must_opt_in_to_one, "Please choose one")
    end

    validates_presence_of :phone, message: "Please add your phone number" if text_opt_in
    validates_presence_of :email, message: "Please add your email address" if email_opt_in
  end

  def address?
    [name, street_address, city, state, zip_code].all?
  end

  def office_address
    case office_choice
    when "Fairbanks District Office"
      {
          name: "Fairbanks District Office",
          address_line1: "675 7th Avenue",
          address_line2: "Station E",
          address_city: "Fairbanks",
          address_state: "AK",
          address_zip: "99701"
      }
    when "Nome District Office"
      {
          name: "Nome District Office",
          address_line1: "214 E. Front Street",
          address_line2: "",
          address_city: "Nome",
          address_state: "AK",
          address_zip: "99762"
      }
    when "Homer District Office"
    {
        name: "Homer District Office",
        address_line1: "3670 Lake Street",
        address_line2: "Suite 200",
        address_city: "Homer",
        address_state: "AK",
        address_zip: "99603"
    }
    when "Kenai Peninsula Job Center"
      {
          name: "Kenai Peninsula Job Center",
          address_line1: "11312 Kenai Spur Hwy",
          address_line2: "Suite 2",
          address_city: "Kenai",
          address_state: "AK",
          address_zip: "99611"
      }
    when "Gambell District Office"
      {
          name: "Gambell District Office",
          address_line1: "400 Gambell Street",
          address_line2: "",
          address_city: "Anchorage",
          address_state: "AK",
          address_zip: "99501"
      }
    when "Muldoon District Office"
      {
          name: "Muldoon District Office",
          address_line1: "1251 Muldoon Road",
          address_line2: "Suite 111B",
          address_city: "Anchorage",
          address_state: "AK",
          address_zip: "99504"
      }
    when "Mat-Su District Office"
      {
          name: "Mat-Su District Office",
          address_line1: "855 W. Commercial Drive",
          address_line2: "",
          address_city: "Wasilla",
          address_state: "AK",
          address_zip: "99654"
      }
    when "Juneau District Office"
      {
          name: "Juneau District Office",
          address_line1: "10002 Glacier Hwy",
          address_line2: "Suite 200",
          address_city: "Juneau",
          address_state: "AK",
          address_zip: "99801"
      }
    when "Ketchikan District Office"
      {
          name: "Ketchikan District Office",
          address_line1: "2030 Sea Level Drive",
          address_line2: "Suite 301",
          address_city: "Ketchikan",
          address_state: "AK",
          address_zip: "99901"
      }
    when "Sitka District Office"
      {
          name: "Sitka District Office",
          address_line1: "304 Lake Street",
          address_line2: "Suite 101",
          address_city: "Sitka",
          address_state: "AK",
          address_zip: "99835"
      }
    when "Kodiak District Office"
      {
          name: "Kodiak District Office",
          address_line1: "211 Mission Road",
          address_line2: "Suite 101",
          address_city: "Kodiak",
          address_state: "AK",
          address_zip: "99615"
      }
    else
      raise "Invalid Office"
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    redirect_to "/upload"
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      session[:current_client_id] = @client.id
      redirect_to @client
    else
      render :new
    end
  end

  def update
    authenticate_admin!

    @client = Client.find params[:id]
    @client.update client_params

    redirect_to "/admin"
  end

  def show
    @client = Client.find params[:id]

    redirect_to root_path unless current_client == @client
    @feedback = Feedback.new
  end

  private

  # Only allow a trusted parameter "white list" through.
  def client_params
    params.require(:client).permit(:phone, :text_opt_in, :email, :email_opt_in, :office_choice, :document, :name, :street_address, :city, :state, :zip_code)
  end
end

app/views/clients/_client.html.erb
<div class="grid__item width-full">
  <div class="admin-application-card">
    <div class="admin-application-card__top">
      <div class="admin-application-card__left">
        <h3><%= client.id %></h3>

        <div class="admin-application-card__data-group">
          <div class="admin-application-card__data">
            <p>Text Opt In - <%= client.text_opt_in.to_s %> - <%= client.phone %></p>
            <p>Email Opt In - <%= client.email_opt_in.to_s %> - <%= client.email %></p>
          </div>
        </div>

        <% if client.address? %>
          <p><%= client.name %></p>
          <p><%= client.street_address %></p>
          <p><%= client.city %></p>
          <p><%= client.state %></p>
          <p><%= client.zip_code %></p>
        <% else %>
          <div class="admin-application-card__data-group">
            <div class="admin-application-card__data">
              <%= form_for(client, builder: CustomCfaFormBuilder) do |form| %>
                <%= form.cfa_input_field :name, "Name" %>
                <%= form.cfa_input_field :street_address, "Street Address" %>
                <%= form.cfa_input_field :city, "City" %>
                <%= form.cfa_input_field :state, "State" %>
                <%= form.cfa_input_field :zip_code, "Zip Code" %>
                <%= form.submit "Add address", class: "button" %>
              <% end %>
            </div>
          </div>
        <% end %>

      </div>

      <div class="admin-application-card__right">
        <p><%= client.created_at.strftime("%m-%d-%Y") %></p>
        <%= link_to "Application Link", pdf_path(client) %>
      </div>
    </div>

    <% if client.address? %>
    <hr />
      <% if client.mailed? %>
        <button class="button button--small with-padding-small" disabled>Mailed <i class="icon-done"></i></button>
      <% else %>
        <%= link_to "Mail Application to State", mail_pdf_path(client.id), class: "button button--danger button--small with-padding-small", method: :post %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/clients/new.html.erb
<div class="slab">
  <main id="main" class="form-card">
    <%= form_with(model: @client, local: true, builder: CustomCfaFormBuilder) do |form| %>
      <header class="form-card__header">
        <h1 class="form-card__title">
          Submit your completed application.
        </h1>
      </header>

      <div class="form-card__content">
        <%= form.cfa_file_upload(
              :document,
              label_text: 'Upload your filled out PDF application.',
              desktop_button_text: 'Pick a file from this computer',
              mobile_button_text: 'Pick a file from this device',
              accept: "application/pdf"
            ) %>

        <%= form.cfa_select(
          :office_choice,
          "What is your local Public Assistance Office?",
          {
            'Northern': ['Fairbanks District Office','Nome District Office'],
            'Peninsula': ['Homer District Office','Kenai Peninsula Job Center'],
            'Southcentral – Anchorage/ Mat-Su': ['Gambell District Office', 'Muldoon District Office', 'Mat-Su District Office'],
            'Southeast': ['Juneau District Office', 'Ketchikan District Office', 'Sitka District Office'],
            'Southwest': ['Bethel District Office', 'Kodiak District Office']
          },
          help_text: 'You can <a href="http://dhss.alaska.gov/dpa/Pages/contacts.aspx" target="_blank">call an office</a> if you are not sure which one to pick.',
        )%>

        <%= form.cfa_checkbox_set_with_follow_up(
          :must_opt_in_to_one,
          [
            { method: :text_opt_in, label: "Text message", data_follow_up: { method: :phone, label: 'Phone number', type: "tel" } },
            { method: :email_opt_in, label: "Email", data_follow_up: { method: :email, label: 'Email', type: "email" } }
          ],
          label_text: "How can we contact you to let you know your application has been mailed?"
        ) %>
      </div>

      <div class="form-card__footer">
        <footer class="form-card__button_right">
          <button class="button button--nav  button--primary button--full-mobile" type="submit">
            Submit my application
          </button>
        </footer>
      </div>
    <% end %>
  </main>
</div>

app/views/clients/show.html.erb
<% content_for :google_ads_conversion do %>
  <!-- Event snippet for Uploaded Application conversion page -->
  <script>
    gtag('event', 'conversion', {
        'send_to': 'AW-780066360/k5K9CJPs2p0BELi8-_MC',
        'value': 1.0
    });
  </script>
<% end %>

<div class="slab">
  <main id="main" class="form-card form-card--transition">
    <header class="form-card__header form-card__header--confirmation">
      <div class="emoji emoji--big emoji--checkmark"></div>
      <h1 class="form-card__title">Your application will be mailed within 24 hours.</h1>
    </header>

    <div class="form-card__content text--centered">
      <h3>What's next?</h3>
      <p>Once your application is in the mail, we’ll send you a confirmation with tracking information and expected arrival time.</p>

      <div id="feedback-container">
        <%= form_for @feedback, remote: true, builder: CustomCfaFormBuilder do |form| %>
          <%= form.cfa_radio_set :rating,
            label_text: "<h3>How was your experience with this tool?</h3>",
            collection: [
              { value: "negative", label: '<span class="radio-button__image emoji emoji--med emoji--frowning-face">Bad</span>' },
              { value: "neutral", label: '<span class="radio-button__image emoji emoji--med emoji--neutral-face">Ok</span>' },
              { value: "positive", label: '<span class="radio-button__image emoji emoji--med emoji--grinning-face">Good</span>' }
            ],
            layouts: ["inline", "image"] %>

          <%= form.cfa_textarea :comments, '<h3>Do you have any feedback for us?</h3>', options: {rows: '2'} %>
          <button class="button button--full-mobile" type="submit">Submit</button>
        <% end %>
      </div>

    </div>
  </main>
</div>